//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace allianceP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Vente
    {
        [DataMember]
        public int VenteID { get; set; }
        [DataMember]
        public Nullable<System.DateTime> dateVente { get; set; }
        [DataMember]
        public Nullable<int> quantity { get; set; }
        [DataMember]
        public Nullable<int> total { get; set; }
        [DataMember]
        public int ClientID { get; set; }
        [DataMember]
        public int ProductID { get; set; }
        [Key]
        [ForeignKey("ClientID")]
        public virtual Clients Clients { get; set; }
        [Key]
        [ForeignKey("ProductID")]
        public virtual Products Products { get; set; }
    }
}
