//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlliancP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productID { get; set; }
        public string name { get; set; }
        public int providerID { get; set; }
        public Nullable<int> stockQuantity { get; set; }
        public string category { get; set; }
    }
}
