//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlliancP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        public int venteID { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<System.DateTime> dateVente { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
